business-category: 52
business-category-details: https://share.philips.com/sites/SWCoE/Lists/List%20of%20Business%20Categories/DispForm.aspx?ID=52
version: '1'
export-control-eccn: EAR99
export-control-sgi: 3
export-control-rationale: Based on export control screening questionnaire results
