ENABLE:
  - ACTION
  - MARKDOWN
  - REPOSITORY
  - SPELL
  - XML
  - YAML
DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS
  - REPOSITORY_SEMGREP
  - SPELL_CSPELL
  - SPELL_PROSELINT
DISABLE_ERRORS_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - SPELL_LYCHEE
PRINT_ALPACA: false
FLAVOR_SUGGESTIONS: false
SHOW_SKIPPED_LINTERS: false
FILTER_REGEX_EXCLUDE: (hal_st/middlewares/STM32_WPAN/)
